#Client Service
apiVersion: v1
kind: Service
metadata:
  name: yoloclient-service
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31110

#Client Deployment manifest
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: yolo-clientapp
          image: docker.io/harold7/yolo-clientapp:1.0.0
          ports:
            - containerPort: 3000
