#Client Service
apiVersion: v1
kind: Service
metadata:
  name: yoloclient-service
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31110