---
- name: Containerized e-commerce platform on Ansible playbook
  hosts: all
  become: true
  vars:
    yolo_app_location: /home/harold/Moringa/yolo

  tasks:

  - name: Install git
    yum: name=git update_cache=yes

  - name: Clone a github repository
    git:
      repo: https://github.com/NelsonOngany/yolo.git
      dest: /Home/Moringa/yolo/
      clone: yes
      update: yes
  
  - name: Install Python packages
    yum:
      name=python3-pip name=python3-setuptools name=python3-requests

  - name: Install Docker
    yum:
      name=docker  

  - name: Install nodejs and npm
    yum: name=nodejs  name=npm update_cache=yes

  - name: Install Forever (to run our Node.js app).
    npm: name=forever global=yes state=present

  - name: Ensure Node.js app folder exists.
    file: "path={{ yolo_app_location }} state=directory"

  - name: Backend docker
    docker_container: 
      name: backend
      image: docker.io/harold7/yolo-backendapp:1.0.0
      ports:
        - "5000:5000"
      command: npm run start

  - name: Client docker
    docker_container: 
      name: client
      image: docker.io/harold7/yolo-clientapp:1.0.0
      ports:
        - "3000:3000"
      command: npm run start

  #- name: Copy example Node.js app to server.
   # copy: "src=app dest={{ yolo_app_location }}"

  #- name: Install app dependencies defined in package.json.
   # npm: "pathS={{ yolo_app_location }} state=present"

  #- name: Check list of running Node.js apps.
   # command: forever list
    #register: forever_list
    #changed_when: false

  #- name: Start example Node.js app.
   # command: "forever start {{yolo_app_location }}/app/app.js"
    #when: "forever_list.stdout.find(yolo_app_location + '/app/app.js') == -1"
    