---
- name: Containerized e-commerce platform on Ansible playbook
  host: all
  become: true
  tasks:
  - name: Clone a github repository
    git:
      repo: https://github.com/NelsonOngany/yolo.git
      dest: /Home/Moringa/yolo/
      clone: yes
      update: yes

  - name: Install nodejs and npm
    apt: name=nodejs  name=npm update_cache=yes
    state: present
